In [5]:
import numpy as np
a=np.array([
    [
        [1,2,3],[24,56,23]]],dtype=int)
b=a.reshape(3,2)
print(b)

[[ 1  2]
 [ 3 24]
 [56 23]]


In [1]:
import time
import  numpy as np
start=time.time()
a=np.arange(100000000)
b=np.arange(100000000,200000000)
c=a+b

print(time.time()-start)

0.4920783042907715


BROAD-CASTING

In [10]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([1,1,2,3])
c=a*b
print(c.reshape(4,1))
aa = np.array([[0.0, 0.0, 0.0], [10.0, 10.0, 10.0], [20.0, 20.0, 20.0], [30.0, 30.0, 30.0]])
bb = np.array([1.0, 2.0, 3.0])
print(aa+bb)

[[ 1]
 [ 2]
 [ 6]
 [12]]
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


ITERATING OVER AN ARRAY

In [27]:
import numpy as np
a=np.arange(0,60,5)
a=a.reshape(3,4)
print(a)
for i in np.nditer(a):
    print(i,end=' ')
b=a.T
for i in np.nditer(b):
    print(i,end=' ')


[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0 5 10 15 20 25 30 35 40 45 50 55 0 5 10 15 20 25 30 35 40 45 50 55 

MANIPULATION

In [28]:
import numpy as np
a = np.arange(8)
print('The original array:')
print(a)
b = a.reshape(4,2)
print('The modified array:')
print(b)

The original array:
[0 1 2 3 4 5 6 7]
The modified array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


FLATTEN

In [35]:
import numpy as np
a = np.arange(0,60,5).reshape(3,2,2)
print(a)

print(a.flat[4])

[[[ 0  5]
  [10 15]]

 [[20 25]
  [30 35]]

 [[40 45]
  [50 55]]]
20


TRANSPOSE

In [41]:
import numpy as np
a=np.arange(8).reshape(2,4)
b=a.T
print(b)

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


CONCATENATE

In [46]:
import numpy as np
a=np.array([[1,2],[4,7]])
b=np.array([[6,7],[90,4]])
c=np.concatenate((a,b),axis=1)
print(c)

[[ 1  2  6  7]
 [ 4  7 90  4]]


JOINING BY STACK

In [48]:
import numpy as np
a=np.array([[3,4],[7,8]])
b=np.array([[5,6],[7,3]])
c=np.stack((a,b),1)
print(c)

[[[3 4]
  [5 6]]

 [[7 8]
  [7 3]]]


In [49]:
import numpy as np
a=np.array([[3,4],[7,8]])
b=np.array([[5,6],[7,3]])
c=np.hstack((a,b))
print(c)

[[3 4 5 6]
 [7 8 7 3]]


In [50]:
import numpy as np
a=np.array([[3,4],[7,8]])
b=np.array([[5,6],[7,3]])
c=np.vstack((a,b))
print(c)

[[3 4]
 [7 8]
 [5 6]
 [7 3]]


SPLITTING ARRAYS

In [58]:
import numpy as np
a = np.array([5, 4, 6, 7, 8, 44, 34, 2, 3, 12])
b = np.split(a, [2,5])  
print(b)


[array([5, 4]), array([6, 7, 8]), array([44, 34,  2,  3, 12])]


In [61]:
import numpy as np
a = np.array([5, 4, 6, 7, 8, 44, 34, 2, 3, 12])
b = np.hsplit(a,2)  
print(b)


[array([5, 4, 6, 7, 8]), array([44, 34,  2,  3, 12])]


RESIZING

In [64]:
import numpy as np
a= np.array([[1,2,3,4],[2,3,4,5]])
b = np.resize(a, (3,2))
print(b)

[[1 2]
 [3 4]
 [2 3]]


In [ ]:
import numpy as np
a = np.arange(0,60,5).reshape(3,2,2)
print(a)

print(a.flat[4])

[[[ 0  5]
  [10 15]]

 [[20 25]
  [30 35]]

 [[40 45]
  [50 55]]]
20


NumPy - Mathematical Functions

In [69]:
import numpy as np
a = np.array([0,30,45,60,90])
b=np.sin(a*np.pi/180)
print(np.degrees(np.arcsin(b)))

[ 0. 30. 45. 60. 90.]


In [66]:
import numpy as np
a = np.array([0,30,45,60,90])
print(np.cos(a*np.pi/180))

[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [71]:
import numpy as np
a = np.array([1.0,5.55, 123, 0.567, 25.532])
print(np.around(a))
print(np.ceil(a))
print(np.floor(a))

[  1.   6. 123.   1.  26.]
[  1.   6. 123.   1.  26.]
[  1.   5. 123.   0.  25.]


NumPy - Arithmetic Operations

In [75]:
import numpy as np
a=np.arange(9,dtype=float).reshape(3,3)
b=np.array([20,20,20])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[20. 21. 22.]
 [23. 24. 25.]
 [26. 27. 28.]]
[[-20. -19. -18.]
 [-17. -16. -15.]
 [-14. -13. -12.]]
[[  0.  20.  40.]
 [ 60.  80. 100.]
 [120. 140. 160.]]
[[0.   0.05 0.1 ]
 [0.15 0.2  0.25]
 [0.3  0.35 0.4 ]]


In [78]:
import numpy as np
a = np.array([-5.6j, 0.2j, 11. , 1+1j])
print(np.real(a))
print(np.imag(a))
print(np.conj(a))
print(np.angle(a,deg=True))


[-0.  0. 11.  1.]
[-5.6  0.2  0.   1. ]
[-0.+5.6j  0.-0.2j 11.-0.j   1.-1.j ]
[-90.  90.   0.  45.]


In [ ]:
import numpy as np
list=[2,34,45,24,4]
numpyarray=np.array(list)
print(numpyarray)

(5,)


In [6]:
import numpy as np
a=np.zeros((8,8),dtype=int)
a[1::2, ::2] = 1  
a[::2, 1::2] = 1 
print(a)




[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [9]:
import numpy as np
list = [1, 2, 3, 4, 5]
tuple = (6, 7, 8, 9, 10)
array_list = np.array(list)
array_tuple = np.array(tuple)
print(array_list)
print(array_tuple)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [5]:
import numpy as np

matrix = np.zeros((4, 4))

np.fill_diagonal(matrix, [4,5,6,8])

print(matrix)






[[4. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 6. 0.]
 [0. 0. 0. 8.]]


In [9]:
import numpy as np
b=np.array([12,34,45,342,45])

print("memory:",b.nbytes)

memory: 20


In [11]:
import numpy as np

celsius_array =np.array([0, 12, 45.21, 34, 99.91])
fahrenheit_array = (celsius_array * 9/5) + 32
print(fahrenheit_array)


[ 32.     53.6   113.378  93.2   211.838]
